---
- hosts: all
  become: yes
  tasks:
  - name: update all packages
    ansible.builtin.apt:
      update_cache: true
      name: "*"
      state: latest
  - name: cleanup
    ansible.builtin.apt:
      autoremove: yes
      autoclean: yes
